# -*- coding: utf-8 -*-
"""self-pruning-nn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKOAGpXsudhLpJD3fQdqdy3ltuVw-T1n
"""

!pip install torch torchvision matplotlib

import torch

print("CUDA Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected")

!nvidia-smi

# INSTALL
!pip install torch torchvision matplotlib

# CHECK GPU

import torch
print("CUDA Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# IMPORTS

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

# DEVICE

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", DEVICE)

# PRUNABLE LAYER

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        self.bias = nn.Parameter(torch.zeros(out_features))
        self.gate_scores = nn.Parameter(torch.zeros(out_features, in_features))
        nn.init.kaiming_uniform_(self.weight, a=0.01)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weight = self.weight * gates
        return F.linear(x, pruned_weight, self.bias)

# MODEL

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = PrunableLinear(3072, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

    def prunable_layers(self):
        for m in self.modules():
            if isinstance(m, PrunableLinear):
                yield m

# SPARSITY LOSS

def sparsity_loss(model):
    loss = 0
    for layer in model.prunable_layers():
        gates = torch.sigmoid(layer.gate_scores)
        loss += gates.sum()
    return loss

# DATA

def get_data(batch_size=64):
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
    ])

    train = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
    test = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

    pin = True if torch.cuda.is_available() else False

    train_loader = DataLoader(train, batch_size=batch_size, shuffle=True, pin_memory=pin)
    test_loader = DataLoader(test, batch_size=128, shuffle=False, pin_memory=pin)

    return train_loader, test_loader

# TRAIN

def train(model, loader, optimizer, lam):
    model.train()
    for imgs, labels in loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)

        optimizer.zero_grad()
        out = model(imgs)

        ce = F.cross_entropy(out, labels)
        sp = sparsity_loss(model)
        loss = ce + lam * sp

        loss.backward()
        optimizer.step()

# TEST

def test(model, loader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for imgs, labels in loader:
            imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
            preds = model(imgs).argmax(1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    return 100 * correct / total

# SPARSITY %

def sparsity(model, threshold=1e-2):
    total = 0
    pruned = 0
    for layer in model.prunable_layers():
        gates = torch.sigmoid(layer.gate_scores)
        total += gates.numel()
        pruned += (gates < threshold).sum().item()
    return 100 * pruned / total

# RUN

train_loader, test_loader = get_data()

LAMBDAS = [0.0001, 0.001, 0.01]
EPOCHS = 25

results = []

for lam in LAMBDAS:
    print("\nRunning lambda =", lam)
    model = Net().to(DEVICE)
    opt = optim.Adam(model.parameters(), lr=0.001)

    for epoch in range(EPOCHS):
        train(model, train_loader, opt, lam)

    acc = test(model, test_loader)
    sp = sparsity(model)

    print("Accuracy:", acc)
    print("Sparsity:", sp)

    results.append((lam, acc, sp))

# RESULTS

print("\nFINAL RESULTS")
for r in results:
    print("Lambda:", r[0], "Acc:", r[1], "Sparsity:", r[2])